# Generated by Django 4.1.2 on 2022-10-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_gender_alter_employee_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='natinality',
            new_name='nationality',
        ),
    ]
